# Generated by Django 6.0.1 on 2026-02-18 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_creator'),
        ('groups', '0002_event_banned_users_event_creator_event_games_and_more'),
        ('schedule', '0002_availability_schedule'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='blocked',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='block_blocked', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='blocking',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='block_blocking', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='user_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friendship_user_1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='user_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friendship_user_2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mutedevent',
            name='muted',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='muted_event_muted', to='groups.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mutedevent',
            name='muting',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='muted_event_muting', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mutedsquad',
            name='muted',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='muted_squad_muted', to='groups.squad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mutedsquad',
            name='muting',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='muted_squad_muting', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muteduser',
            name='muted',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='muted_user_muted', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muteduser',
            name='muting',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='muted_user_muting', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(through='users.Block', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(through='users.Friendship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(to='games.game'),
        ),
        migrations.AddField(
            model_name='user',
            name='muted_events',
            field=models.ManyToManyField(related_name='user_muted_events', through='users.MutedEvent', to='groups.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='muted_squads',
            field=models.ManyToManyField(related_name='user_muted_squads', through='users.MutedSquad', to='groups.squad'),
        ),
        migrations.AddField(
            model_name='user',
            name='muted_users',
            field=models.ManyToManyField(related_name='user_muted_users', through='users.MutedUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='schedule',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_schedule', to='schedule.schedule'),
            preserve_default=False,
        ),
    ]
