# Generated by Django 6.0.1 on 2026-02-17 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_creator'),
        ('groups', '0002_ban_event_ban_squad_ban_user_event_creator_and_more'),
        ('schedule', '0002_availability_schedule_schedule_event_schedule_player_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='blocked',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='block_blocked', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='blocking',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='block_blocking', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='user_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friendship_user_1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='user_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friendship_user_2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silenced',
            name='agent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='silenced_agent', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silenced',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silenced_event', to='groups.event'),
        ),
        migrations.AddField(
            model_name='silenced',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silenced_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='silenced',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silenced_squad', to='groups.squad'),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_players',
            field=models.ManyToManyField(through='users.Block', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(through='users.Friendship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='game_preferences',
            field=models.ManyToManyField(to='games.game'),
        ),
        migrations.AddField(
            model_name='user',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_schedule', to='schedule.schedule'),
        ),
    ]
