# Generated by Django 6.0.1 on 2026-02-17 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_event_banned_players_event_creator_event_games_and_more'),
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='schedule',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedule', to='schedule.schedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_event', to='groups.event'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='squad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_squad', to='groups.squad'),
        ),
    ]
