# Generated by Django 6.0.1 on 2026-02-22 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_availability_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedule', to='schedule.schedule'),
        ),
    ]
