# Generated by Django 6.0.1 on 2026-02-16 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='schedule',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedule', to='schedule.schedule'),
            preserve_default=False,
        ),
    ]
