# Generated by Django 6.0.1 on 2026-02-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_event_schedule_player_schedule_squad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='event',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='player',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='squad',
        ),
    ]
