# Generated by Django 6.0.1 on 2026-02-17 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_creator'),
        ('groups', '0001_initial'),
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banned_players',
            field=models.ManyToManyField(related_name='event_banned_players', through='groups.EventBan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='games',
            field=models.ManyToManyField(to='games.game'),
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.squad'),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event_host', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(related_name='event_members', through='groups.EventMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_schedule', to='schedule.schedule'),
        ),
        migrations.AddField(
            model_name='eventban',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_ban_event', to='groups.event'),
        ),
        migrations.AddField(
            model_name='eventban',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_ban_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event_member_event', to='groups.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmember',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event_member_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squad',
            name='banned_players',
            field=models.ManyToManyField(related_name='squad_banned_players', through='groups.SquadBan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squad',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='squad_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squad',
            name='games',
            field=models.ManyToManyField(to='games.game'),
        ),
        migrations.AddField(
            model_name='squad',
            name='host',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='squad_host', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squad',
            name='members',
            field=models.ManyToManyField(related_name='squad_members', through='groups.SquadMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squad',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squad_schedule', to='schedule.schedule'),
        ),
        migrations.AddField(
            model_name='squadban',
            name='squad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='squad_ban_squad', to='groups.squad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squadban',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='squad_ban_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squadmember',
            name='squad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='squad_member_squad', to='groups.squad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squadmember',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='squad_member_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
