# Generated by Django 6.0.1 on 2026-02-16 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_ban_event_ban_squad_ban_user_event_creator_and_more'),
        ('schedule', '0005_schedule_event_schedule_player_schedule_squad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_schedule', to='schedule.schedule'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squad_schedule', to='schedule.schedule'),
        ),
    ]
