# Generated by Django 6.0.1 on 2026-02-17 14:59

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_event_banned_players_event_creator_event_games_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squadban',
            options={'base_manager_name': 'ban_manager'},
        ),
        migrations.AlterModelOptions(
            name='squadmember',
            options={'base_manager_name': 'membership_manager'},
        ),
        migrations.AlterModelManagers(
            name='squadban',
            managers=[
                ('ban_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='squadmember',
            managers=[
                ('membership_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
