# Generated by Django 6.0.1 on 2026-02-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_squadban_options_alter_squadmember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squadban',
            options={},
        ),
        migrations.AlterModelOptions(
            name='squadmember',
            options={},
        ),
        migrations.AlterModelManagers(
            name='squadban',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='squadmember',
            managers=[
            ],
        ),
    ]
